unit usctypes;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils;

type
  TSwitchValue = (svClear, svSet, svRandomize, svToggle);
  ArrayOfSwitchValue = array of TSwitchValue;
  TSetIntegerMode = (simSetTo, simAdd, simSubtract);
  TStarcraftScore = (ssTotalScore, ssUnitScore, ssBuildingScore, ssUnitAndBuildingScore,
                   ssKillScore, ssRazingScore, ssKillAndRazingScore,
                   ssCustomScore);
  TStarcraftResource = (srOre, srGas, srOreAndGas);
  TIntegerConditionMode = (icmAtLeast,icmAtMost,icmExactly);
  TUnitOrder = (uoMove, uoPatrol, uoAttack);
  TAllianceStatus = (asEnnemy, asAlly, asAlliedVictory);

const
  BoolToSwitch : array[Boolean] of TSwitchValue = (svClear, svSet);

type
  TPlayer = (plNone, plPlayer1, plPlayer2, plPlayer3, plPlayer4,
             plPlayer5, plPlayer6, plPlayer7, plPlayer8,
             plPlayer9, plPlayer10, plPlayer11, plPlayer12,
             plUnknown13, plCurrentPlayer, plFoes, plAllies,
             plNeutralPlayers, plAllPlayers,
             plForce1, plForce2, plForce3, plForce4,
             plUnknown23, plUnknown24, plUnknown25, plUnknown26,
             plNonAlliedVictoryPlayers);
  TPlayers = set of TPlayer;

function IntToPlayer(APlayer: integer): TPlayer;
function IsUniquePlayer(APlayers: TPlayers): boolean;

const
  MaxTriggerPlayers = 8;
  MaxSwitches = 256;
  PlayerIdentifiers : array[TPlayer] of string =
    ('', 'Player1', 'Player2', 'Player3', 'Player4',
    'Player5', 'Player6', 'Player7', 'Player8',
    'Player9', 'Player10', 'Player11', 'Player12',
    '', 'Me', 'Foes', 'Allies',
    'NeutralPlayers', 'AllPlayers',
    'Force1', 'Force2', 'Force3', 'Force4',
    '', '', '', '', 'NonAlliedVictoryPlayers');

type
  TUnitProperties = packed record
    Resource, HangarCount: integer;
    Life, Shield, Energy: byte;
    Invincible, Burrowed, Lifted, Hallucinated, Cloaked: ByteBool;
  end;

  TAIScript = record
    Code: string;
    Identifier: string;
  end;

const
  AIScripts: array[1..293] of TAIScript = (
    (Code: 'JYDg'; Identifier: 'JunkYardDog'),
    (Code: 'HaHe'; Identifier: 'AIHarassHere'),
    (Code: 'NuHe'; Identifier: 'AINukeHere'),
    (Code: 'PB1A'; Identifier: 'BroodWarProtoss1TownA'),
    (Code: 'PB1B'; Identifier: 'BroodWarProtoss1TownB'),
    (Code: 'PB1C'; Identifier: 'BroodWarProtoss1TownC'),
    (Code: 'PB1D'; Identifier: 'BroodWarProtoss1TownD'),
    (Code: 'PB1E'; Identifier: 'BroodWarProtoss1TownE'),
    (Code: 'PB1F'; Identifier: 'BroodWarProtoss1TownF'),
    (Code: 'PB2A'; Identifier: 'BroodWarProtoss2TownA'),
    (Code: 'PB2B'; Identifier: 'BroodWarProtoss2TownB'),
    (Code: 'PB2C'; Identifier: 'BroodWarProtoss2TownC'),
    (Code: 'PB2D'; Identifier: 'BroodWarProtoss2TownD'),
    (Code: 'PB2E'; Identifier: 'BroodWarProtoss2TownE'),
    (Code: 'PB2F'; Identifier: 'BroodWarProtoss2TownF'),
    (Code: 'PB3A'; Identifier: 'BroodWarProtoss3TownA'),
    (Code: 'PB3B'; Identifier: 'BroodWarProtoss3TownB'),
    (Code: 'PB3C'; Identifier: 'BroodWarProtoss3TownC'),
    (Code: 'PB3D'; Identifier: 'BroodWarProtoss3TownD'),
    (Code: 'PB3E'; Identifier: 'BroodWarProtoss3TownE'),
    (Code: 'PB3F'; Identifier: 'BroodWarProtoss3TownF'),
    (Code: 'PB4A'; Identifier: 'BroodWarProtoss4TownA'),
    (Code: 'PB4B'; Identifier: 'BroodWarProtoss4TownB'),
    (Code: 'PB4C'; Identifier: 'BroodWarProtoss4TownC'),
    (Code: 'PB4D'; Identifier: 'BroodWarProtoss4TownD'),
    (Code: 'PB4E'; Identifier: 'BroodWarProtoss4TownE'),
    (Code: 'PB4F'; Identifier: 'BroodWarProtoss4TownF'),
    (Code: 'PB5A'; Identifier: 'BroodWarProtoss5TownA'),
    (Code: 'PB5B'; Identifier: 'BroodWarProtoss5TownB'),
    (Code: 'PB5C'; Identifier: 'BroodWarProtoss5TownC'),
    (Code: 'PB5D'; Identifier: 'BroodWarProtoss5TownD'),
    (Code: 'PB5E'; Identifier: 'BroodWarProtoss5TownE'),
    (Code: 'PB5F'; Identifier: 'BroodWarProtoss5TownF'),
    (Code: 'PB6A'; Identifier: 'BroodWarProtoss6TownA'),
    (Code: 'PB6B'; Identifier: 'BroodWarProtoss6TownB'),
    (Code: 'PB6C'; Identifier: 'BroodWarProtoss6TownC'),
    (Code: 'PB6D'; Identifier: 'BroodWarProtoss6TownD'),
    (Code: 'PB6E'; Identifier: 'BroodWarProtoss6TownE'),
    (Code: 'PB6F'; Identifier: 'BroodWarProtoss6TownF'),
    (Code: 'PB7A'; Identifier: 'BroodWarProtoss7TownA'),
    (Code: 'PB7B'; Identifier: 'BroodWarProtoss7TownB'),
    (Code: 'PB7C'; Identifier: 'BroodWarProtoss7TownC'),
    (Code: 'PB7D'; Identifier: 'BroodWarProtoss7TownD'),
    (Code: 'PB7E'; Identifier: 'BroodWarProtoss7TownE'),
    (Code: 'PB7F'; Identifier: 'BroodWarProtoss7TownF'),
    (Code: 'PB8A'; Identifier: 'BroodWarProtoss8TownA'),
    (Code: 'PB8B'; Identifier: 'BroodWarProtoss8TownB'),
    (Code: 'PB8C'; Identifier: 'BroodWarProtoss8TownC'),
    (Code: 'PB8D'; Identifier: 'BroodWarProtoss8TownD'),
    (Code: 'PB8E'; Identifier: 'BroodWarProtoss8TownE'),
    (Code: 'PB8F'; Identifier: 'BroodWarProtoss8TownF'),
    (Code: 'TB1A'; Identifier: 'BroodWarTerran1TownA'),
    (Code: 'TB1B'; Identifier: 'BroodWarTerran1TownB'),
    (Code: 'TB1C'; Identifier: 'BroodWarTerran1TownC'),
    (Code: 'TB1D'; Identifier: 'BroodWarTerran1TownD'),
    (Code: 'TB1E'; Identifier: 'BroodWarTerran1TownE'),
    (Code: 'TB1F'; Identifier: 'BroodWarTerran1TownF'),
    (Code: 'TB2A'; Identifier: 'BroodWarTerran2TownA'),
    (Code: 'TB2B'; Identifier: 'BroodWarTerran2TownB'),
    (Code: 'TB2C'; Identifier: 'BroodWarTerran2TownC'),
    (Code: 'TB2D'; Identifier: 'BroodWarTerran2TownD'),
    (Code: 'TB2E'; Identifier: 'BroodWarTerran2TownE'),
    (Code: 'TB2F'; Identifier: 'BroodWarTerran2TownF'),
    (Code: 'TB3A'; Identifier: 'BroodWarTerran3TownA'),
    (Code: 'TB3B'; Identifier: 'BroodWarTerran3TownB'),
    (Code: 'TB3C'; Identifier: 'BroodWarTerran3TownC'),
    (Code: 'TB3D'; Identifier: 'BroodWarTerran3TownD'),
    (Code: 'TB3E'; Identifier: 'BroodWarTerran3TownE'),
    (Code: 'TB3F'; Identifier: 'BroodWarTerran3TownF'),
    (Code: 'TB4A'; Identifier: 'BroodWarTerran4TownA'),
    (Code: 'TB4B'; Identifier: 'BroodWarTerran4TownB'),
    (Code: 'TB4C'; Identifier: 'BroodWarTerran4TownC'),
    (Code: 'TB4D'; Identifier: 'BroodWarTerran4TownD'),
    (Code: 'TB4E'; Identifier: 'BroodWarTerran4TownE'),
    (Code: 'TB4F'; Identifier: 'BroodWarTerran4TownF'),
    (Code: 'TB5A'; Identifier: 'BroodWarTerran5TownA'),
    (Code: 'TB5B'; Identifier: 'BroodWarTerran5TownB'),
    (Code: 'TB5C'; Identifier: 'BroodWarTerran5TownC'),
    (Code: 'TB5D'; Identifier: 'BroodWarTerran5TownD'),
    (Code: 'TB5E'; Identifier: 'BroodWarTerran5TownE'),
    (Code: 'TB5F'; Identifier: 'BroodWarTerran5TownF'),
    (Code: 'TB6A'; Identifier: 'BroodWarTerran6TownA'),
    (Code: 'TB6B'; Identifier: 'BroodWarTerran6TownB'),
    (Code: 'TB6C'; Identifier: 'BroodWarTerran6TownC'),
    (Code: 'TB6D'; Identifier: 'BroodWarTerran6TownD'),
    (Code: 'TB6E'; Identifier: 'BroodWarTerran6TownE'),
    (Code: 'TB6F'; Identifier: 'BroodWarTerran6TownF'),
    (Code: 'TB7A'; Identifier: 'BroodWarTerran7TownA'),
    (Code: 'TB7B'; Identifier: 'BroodWarTerran7TownB'),
    (Code: 'TB7C'; Identifier: 'BroodWarTerran7TownC'),
    (Code: 'TB7D'; Identifier: 'BroodWarTerran7TownD'),
    (Code: 'TB7E'; Identifier: 'BroodWarTerran7TownE'),
    (Code: 'TB7F'; Identifier: 'BroodWarTerran7TownF'),
    (Code: 'TB8A'; Identifier: 'BroodWarTerran8TownA'),
    (Code: 'TB8B'; Identifier: 'BroodWarTerran8TownB'),
    (Code: 'TB8C'; Identifier: 'BroodWarTerran8TownC'),
    (Code: 'TB8D'; Identifier: 'BroodWarTerran8TownD'),
    (Code: 'TB8E'; Identifier: 'BroodWarTerran8TownE'),
    (Code: 'TB8F'; Identifier: 'BroodWarTerran8TownF'),
    (Code: 'ZB1A'; Identifier: 'BroodWarZerg10TownA'),
    (Code: 'ZB1B'; Identifier: 'BroodWarZerg10TownB'),
    (Code: 'ZB1C'; Identifier: 'BroodWarZerg10TownC'),
    (Code: 'ZB1D'; Identifier: 'BroodWarZerg10TownD'),
    (Code: 'ZB1E'; Identifier: 'BroodWarZerg10TownE'),
    (Code: 'ZB1F'; Identifier: 'BroodWarZerg10TownF'),
    (Code: 'ZB0A'; Identifier: 'BroodWarZerg1TownA'),
    (Code: 'ZB0B'; Identifier: 'BroodWarZerg1TownB'),
    (Code: 'ZB0C'; Identifier: 'BroodWarZerg1TownC'),
    (Code: 'ZB0D'; Identifier: 'BroodWarZerg1TownD'),
    (Code: 'ZB0E'; Identifier: 'BroodWarZerg1TownE'),
    (Code: 'ZB0F'; Identifier: 'BroodWarZerg1TownF'),
    (Code: 'ZB2A'; Identifier: 'BroodWarZerg2TownA'),
    (Code: 'ZB2B'; Identifier: 'BroodWarZerg2TownB'),
    (Code: 'ZB2C'; Identifier: 'BroodWarZerg2TownC'),
    (Code: 'ZB2D'; Identifier: 'BroodWarZerg2TownD'),
    (Code: 'ZB2E'; Identifier: 'BroodWarZerg2TownE'),
    (Code: 'ZB2F'; Identifier: 'BroodWarZerg2TownF'),
    (Code: 'ZB3A'; Identifier: 'BroodWarZerg3TownA'),
    (Code: 'ZB3B'; Identifier: 'BroodWarZerg3TownB'),
    (Code: 'ZB3C'; Identifier: 'BroodWarZerg3TownC'),
    (Code: 'ZB3D'; Identifier: 'BroodWarZerg3TownD'),
    (Code: 'ZB3E'; Identifier: 'BroodWarZerg3TownE'),
    (Code: 'ZB3F'; Identifier: 'BroodWarZerg3TownF'),
    (Code: 'ZB4A'; Identifier: 'BroodWarZerg4TownA'),
    (Code: 'ZB4B'; Identifier: 'BroodWarZerg4TownB'),
    (Code: 'ZB4C'; Identifier: 'BroodWarZerg4TownC'),
    (Code: 'ZB4D'; Identifier: 'BroodWarZerg4TownD'),
    (Code: 'ZB4E'; Identifier: 'BroodWarZerg4TownE'),
    (Code: 'ZB4F'; Identifier: 'BroodWarZerg4TownF'),
    (Code: 'ZB5A'; Identifier: 'BroodWarZerg5TownA'),
    (Code: 'ZB5B'; Identifier: 'BroodWarZerg5TownB'),
    (Code: 'ZB5C'; Identifier: 'BroodWarZerg5TownC'),
    (Code: 'ZB5D'; Identifier: 'BroodWarZerg5TownD'),
    (Code: 'ZB5E'; Identifier: 'BroodWarZerg5TownE'),
    (Code: 'ZB5F'; Identifier: 'BroodWarZerg5TownF'),
    (Code: 'ZB6A'; Identifier: 'BroodWarZerg6TownA'),
    (Code: 'ZB6B'; Identifier: 'BroodWarZerg6TownB'),
    (Code: 'ZB6C'; Identifier: 'BroodWarZerg6TownC'),
    (Code: 'ZB6D'; Identifier: 'BroodWarZerg6TownD'),
    (Code: 'ZB6E'; Identifier: 'BroodWarZerg6TownE'),
    (Code: 'ZB6F'; Identifier: 'BroodWarZerg6TownF'),
    (Code: 'ZB7A'; Identifier: 'BroodWarZerg7TownA'),
    (Code: 'ZB7B'; Identifier: 'BroodWarZerg7TownB'),
    (Code: 'ZB7C'; Identifier: 'BroodWarZerg7TownC'),
    (Code: 'ZB7D'; Identifier: 'BroodWarZerg7TownD'),
    (Code: 'ZB7E'; Identifier: 'BroodWarZerg7TownE'),
    (Code: 'ZB7F'; Identifier: 'BroodWarZerg7TownF'),
    (Code: 'ZB8A'; Identifier: 'BroodWarZerg8TownA'),
    (Code: 'ZB8B'; Identifier: 'BroodWarZerg8TownB'),
    (Code: 'ZB8C'; Identifier: 'BroodWarZerg8TownC'),
    (Code: 'ZB8D'; Identifier: 'BroodWarZerg8TownD'),
    (Code: 'ZB8E'; Identifier: 'BroodWarZerg8TownE'),
    (Code: 'ZB8F'; Identifier: 'BroodWarZerg8TownF'),
    (Code: 'ZB9A'; Identifier: 'BroodWarZerg9TownA'),
    (Code: 'ZB9B'; Identifier: 'BroodWarZerg9TownB'),
    (Code: 'ZB9C'; Identifier: 'BroodWarZerg9TownC'),
    (Code: 'ZB9D'; Identifier: 'BroodWarZerg9TownD'),
    (Code: 'ZB9E'; Identifier: 'BroodWarZerg9TownE'),
    (Code: 'ZB9F'; Identifier: 'BroodWarZerg9TownF'),
    (Code: 'DWHe'; Identifier: 'CastDisruptionWeb'),
    (Code: 'ReHe'; Identifier: 'CastRecall'),
    (Code: 'ClrC'; Identifier: 'ClearPreviousCombatData'),
    (Code: 'EnBk'; Identifier: 'EnterClosestBunker'),
    (Code: 'EnTr'; Identifier: 'EnterTransport'),
    (Code: 'ExTr'; Identifier: 'ExitTransport'),
    (Code: 'PARx'; Identifier: 'ExpansionProtossCampaignAreaTown'),
    (Code: 'PHIx'; Identifier: 'ExpansionProtossCampaignDifficult'),
    (Code: 'PLOx'; Identifier: 'ExpansionProtossCampaignEasy'),
    (Code: 'PSUx'; Identifier: 'ExpansionProtossCampaignInsane'),
    (Code: 'PMEx'; Identifier: 'ExpansionProtossCampaignMedium'),
    (Code: 'TARx'; Identifier: 'ExpansionTerranCampaignAreaTown'),
    (Code: 'THIx'; Identifier: 'ExpansionTerranCampaignDifficult'),
    (Code: 'TLOx'; Identifier: 'ExpansionTerranCampaignEasy'),
    (Code: 'TSUx'; Identifier: 'ExpansionTerranCampaignInsane'),
    (Code: 'TMEx'; Identifier: 'ExpansionTerranCampaignMedium'),
    (Code: 'ZARx'; Identifier: 'ExpansionZergCampaignAreaTown'),
    (Code: 'ZHIx'; Identifier: 'ExpansionZergCampaignDifficult'),
    (Code: 'ZLOx'; Identifier: 'ExpansionZergCampaignEasy'),
    (Code: 'ZSUx'; Identifier: 'ExpansionZergCampaignInsane'),
    (Code: 'ZMEx'; Identifier: 'ExpansionZergCampaignMedium'),
    (Code: 'StPt'; Identifier: 'MakeTheseUnitsPatrol'),
    (Code: 'MvTe'; Identifier: 'MoveDarkTemplarsToRegion'),
    (Code: 'Pro1'; Identifier: 'Protoss10MiniTownMaster'),
    (Code: 'P10C'; Identifier: 'Protoss10MiniTowns'),
    (Code: 'Pr10'; Identifier: 'Protoss10OvermindDefenders'),
    (Code: 'P10o'; Identifier: 'Protoss1ZergTown'),
    (Code: 'Pro2'; Identifier: 'Protoss2ZergTown'),
    (Code: 'Pr3R'; Identifier: 'Protoss3AirZergTown'),
    (Code: 'Pr3G'; Identifier: 'Protoss3GroundZergTown'),
    (Code: 'Pro4'; Identifier: 'Protoss4ZergTown'),
    (Code: 'Pr5B'; Identifier: 'Protoss5ZergTownBase'),
    (Code: 'Pr5I'; Identifier: 'Protoss5ZergTownIsland'),
    (Code: 'Pro7'; Identifier: 'Protoss7LeftProtossTown'),
    (Code: 'Pr7B'; Identifier: 'Protoss7RightProtossTown'),
    (Code: 'Pr7S'; Identifier: 'Protoss7ShrineProtoss'),
    (Code: 'Pro8'; Identifier: 'Protoss8LeftProtossTown'),
    (Code: 'Pr8D'; Identifier: 'Protoss8ProtossDefenders'),
    (Code: 'Pr8B'; Identifier: 'Protoss8RightProtossTown'),
    (Code: 'Pr9W'; Identifier: 'Protoss9AirZerg'),
    (Code: 'Pro9'; Identifier: 'Protoss9GroundZerg'),
    (Code: 'Pr9Y'; Identifier: 'Protoss9SpellZerg'),
    (Code: 'PARE'; Identifier: 'ProtossCampaignAreaTown'),
    (Code: 'PHIf'; Identifier: 'ProtossCampaignDifficult'),
    (Code: 'PLOf'; Identifier: 'ProtossCampaignEasy'),
    (Code: 'PSUP'; Identifier: 'ProtossCampaignInsane'),
    (Code: 'PMED'; Identifier: 'ProtossCampaignMedium'),
    (Code: 'PMCu'; Identifier: 'ProtossCustomLevel'),
    (Code: 'PMCx'; Identifier: 'ProtossExpansionCustomLevel'),
    (Code: 'SuiR'; Identifier: 'SendAllUnitsOnRandomSuicideMissions'),
    (Code: 'Suic'; Identifier: 'SendAllUnitsOnStrategicSuicideMissions'),
    (Code: 'StTg'; Identifier: 'SetGenericCommandTarget'),
    (Code: 'Ally'; Identifier: 'SetPlayerToAllyHere'),
    (Code: 'Enmy'; Identifier: 'SetPlayerToEnemyHere'),
    (Code: 'Rscu'; Identifier: 'SwitchComputerPlayerToRescuePassive'),
    (Code: 'TED1'; Identifier: 'Terran10CondeferateTowns'),
    (Code: 'TSW1'; Identifier: 'Terran11LowerProtossTown'),
    (Code: 'Te10'; Identifier: 'Terran11UpperProtossTown'),
    (Code: 'T11a'; Identifier: 'Terran11ZergTown'),
    (Code: 'T11b'; Identifier: 'Terran12NukeTown'),
    (Code: 'T11z'; Identifier: 'Terran12PhoenixTown'),
    (Code: 'T12N'; Identifier: 'Terran12TankTown'),
    (Code: 'T12P'; Identifier: 'Terran1ElectronicDistribution'),
    (Code: 'T12T'; Identifier: 'Terran1Shareware'),
    (Code: 'TED2'; Identifier: 'Terran2ElectronicDistribution'),
    (Code: 'TSW2'; Identifier: 'Terran2Shareware'),
    (Code: 'TED3'; Identifier: 'Terran3ElectronicDistribution'),
    (Code: 'TSW3'; Identifier: 'Terran3Shareware'),
    (Code: 'Ter3'; Identifier: 'Terran3ZergTown'),
    (Code: 'TSW4'; Identifier: 'Terran4Shareware'),
    (Code: 'TSW5'; Identifier: 'Terran5Shareware'),
    (Code: 'Te5H'; Identifier: 'Terran5TerranHarvestTown'),
    (Code: 'Ter5'; Identifier: 'Terran5TerranMainTown'),
    (Code: 'Ter6'; Identifier: 'Terran6AirAttackZerg'),
    (Code: 'Te6b'; Identifier: 'Terran6GroundAttackZerg'),
    (Code: 'Te6c'; Identifier: 'Terran6ZergSupportTown'),
    (Code: 'Ter7'; Identifier: 'Terran7BottomZergTown'),
    (Code: 'Te7m'; Identifier: 'Terran7MiddleZergTown'),
    (Code: 'Te7s'; Identifier: 'Terran7RightZergTown'),
    (Code: 'Ter8'; Identifier: 'Terran8CondeferateTown'),
    (Code: 'Tr9H'; Identifier: 'Terran9HeavyAttack'),
    (Code: 'Tr9L'; Identifier: 'Terran9LightAttack'),
    (Code: 'TARE'; Identifier: 'TerranCampaignAreaTown'),
    (Code: 'THIf'; Identifier: 'TerranCampaignDifficult'),
    (Code: 'TLOf'; Identifier: 'TerranCampaignEasy'),
    (Code: 'TSUP'; Identifier: 'TerranCampaignInsane'),
    (Code: 'TMED'; Identifier: 'TerranCampaignMedium'),
    (Code: 'TMCu'; Identifier: 'TerranCustomLevel'),
    (Code: 'TMCx'; Identifier: 'TerranExpansionCustomLevel'),
    (Code: '-Vi0'; Identifier: 'TurnOffSharedVisionOfPlayer1WithCurrentPlayer'),
    (Code: '-Vi1'; Identifier: 'TurnOffSharedVisionOfPlayer2WithCurrentPlayer'),
    (Code: '-Vi2'; Identifier: 'TurnOffSharedVisionOfPlayer3WithCurrentPlayer'),
    (Code: '-Vi3'; Identifier: 'TurnOffSharedVisionOfPlayer4WithCurrentPlayer'),
    (Code: '-Vi4'; Identifier: 'TurnOffSharedVisionOfPlayer5WithCurrentPlayer'),
    (Code: '-Vi5'; Identifier: 'TurnOffSharedVisionOfPlayer6WithCurrentPlayer'),
    (Code: '-Vi6'; Identifier: 'TurnOffSharedVisionOfPlayer7WithCurrentPlayer'),
    (Code: '-Vi7'; Identifier: 'TurnOffSharedVisionOfPlayer8WithCurrentPlayer'),
    (Code: '+Vi0'; Identifier: 'TurnOnSharedVisionOfPlayer1WithCurrentPlayer'),
    (Code: '+Vi1'; Identifier: 'TurnOnSharedVisionOfPlayer2WithCurrentPlayer'),
    (Code: '+Vi2'; Identifier: 'TurnOnSharedVisionOfPlayer3WithCurrentPlayer'),
    (Code: '+Vi3'; Identifier: 'TurnOnSharedVisionOfPlayer4WithCurrentPlayer'),
    (Code: '+Vi4'; Identifier: 'TurnOnSharedVisionOfPlayer5WithCurrentPlayer'),
    (Code: '+Vi5'; Identifier: 'TurnOnSharedVisionOfPlayer6WithCurrentPlayer'),
    (Code: '+Vi6'; Identifier: 'TurnOnSharedVisionOfPlayer7WithCurrentPlayer'),
    (Code: '+Vi7'; Identifier: 'TurnOnSharedVisionOfPlayer8WithCurrentPlayer'),
    (Code: 'VluA'; Identifier: 'ValueThisAreaHigher'),
    (Code: 'Z10a'; Identifier: 'Zerg10LeftTealAttack'),
    (Code: 'Z10c'; Identifier: 'Zerg10LeftYellowSupport'),
    (Code: 'Z10e'; Identifier: 'Zerg10RedProtoss'),
    (Code: 'Z10b'; Identifier: 'Zerg10RightTealSupport'),
    (Code: 'Z10d'; Identifier: 'Zerg10RightYellowAttack'),
    (Code: 'Zer1'; Identifier: 'Zerg1TerranTown'),
    (Code: 'Zer2'; Identifier: 'Zerg2ProtossTown'),
    (Code: 'Zer3'; Identifier: 'Zerg3TerranTown'),
    (Code: 'Ze4S'; Identifier: 'Zerg4LowerTerranTown'),
    (Code: 'Zer4'; Identifier: 'Zerg4RightTerranTown'),
    (Code: 'Zer6'; Identifier: 'Zerg6ProtossTown'),
    (Code: 'Zr7a'; Identifier: 'Zerg7AirTown'),
    (Code: 'Zr7g'; Identifier: 'Zerg7GroundTown'),
    (Code: 'Zr7s'; Identifier: 'Zerg7SupportTown'),
    (Code: 'Zer8'; Identifier: 'Zerg8ScoutTown'),
    (Code: 'Ze8T'; Identifier: 'Zerg8TemplarTown'),
    (Code: 'Z9lo'; Identifier: 'Zerg9LeftOrangeProtoss'),
    (Code: 'Z9ly'; Identifier: 'Zerg9LeftYellowProtoss'),
    (Code: 'Z9ro'; Identifier: 'Zerg9RightOrangeProtoss'),
    (Code: 'Z9ry'; Identifier: 'Zerg9RightYellowProtoss'),
    (Code: 'Zer9'; Identifier: 'Zerg9TealProtoss'),
    (Code: 'ZARE'; Identifier: 'ZergCampaignAreaTown'),
    (Code: 'ZHIf'; Identifier: 'ZergCampaignDifficult'),
    (Code: 'ZLOf'; Identifier: 'ZergCampaignEasy'),
    (Code: 'ZSUP'; Identifier: 'ZergCampaignInsane'),
    (Code: 'ZMED'; Identifier: 'ZergCampaignMedium'),
    (Code: 'ZMCu'; Identifier: 'ZergCustomLevel'),
    (Code: 'ZMCx'; Identifier: 'ZergExpansionCustomLevel') );

type TStarcraftUnit =
   (suTerranMarine,
    suTerranGhost,
    suTerranVulture,
    suTerranGoliath,
    suTerranGoliathTurret,
    suTerranSiegeTankTankMode,
    suTerranSiegeTankTankModeTurret,
    suTerranSCV,
    suTerranWraith,
    suTerranScienceVessel,
    suHeroGuiMontag,
    suTerranDropship,
    suTerranBattlecruiser,
    suTerranVultureSpiderMine,
    suTerranNuclearMissile,
    suTerranCivilian,
    suHeroSarahKerrigan,
    suHeroAlanSchezar,
    suHeroAlanSchezarTurret,
    suHeroJimRaynorVulture,
    suHeroJimRaynorMarine,
    suHeroTomKazansky,
    suHeroMagellan,
    suHeroEdmundDukeTankMode,
    suHeroEdmundDukeTankModeTurret,
    suHeroEdmundDukeSiegeMode,
    suHeroEdmundDukeSiegeModeTurret,
    suHeroArcturusMengsk,
    suHeroHyperion,
    suHeroNoradII,
    suTerranSiegeTankSiegeMode,
    suTerranSiegeTankSiegeModeTurret,
    suTerranFirebat,
    suSpellScannerSweep,
    suTerranMedic,
    suZergLarva,
    suZergEgg,
    suZergZergling,
    suZergHydralisk,
    suZergUltralisk,
    suZergBroodling,
    suZergDrone,
    suZergOverlord,
    suZergMutalisk,
    suZergGuardian,
    suZergQueen,
    suZergDefiler,
    suZergScourge,
    suHeroTorrasque,
    suHeroMatriarch,
    suZergInfestedTerran,
    suHeroInfestedKerrigan,
    suHeroUncleanOne,
    suHeroHunterKiller,
    suHeroDevouringOne,
    suHeroKukulzaMutalisk,
    suHeroKukulzaGuardian,
    suHeroYggdrasill,
    suTerranValkyrie,
    suZergCocoon,
    suProtossCorsair,
    suProtossDarkTemplar,
    suZergDevourer,
    suProtossDarkArchon,
    suProtossProbe,
    suProtossZealot,
    suProtossDragoon,
    suProtossHighTemplar,
    suProtossArchon,
    suProtossShuttle,
    suProtossScout,
    suProtossArbiter,
    suProtossCarrier,
    suProtossInterceptor,
    suHeroDarkTemplar,
    suHeroZeratul,
    suHeroTassadarZeratulArchon,
    suHeroFenixZealot,
    suHeroFenixDragoon,
    suHeroTassadar,
    suHeroMojo,
    suHeroWarbringer,
    suHeroGantrithor,
    suProtossReaver,
    suProtossObserver,
    suProtossScarab,
    suHeroDanimoth,
    suHeroAldaris,
    suHeroArtanis,
    suCritterRhynadon,
    suCritterBengalaas,
    suSpecialCargoShip,
    suSpecialMercenaryGunship,
    suCritterScantid,
    suCritterKakaru,
    suCritterRagnasaur,
    suCritterUrsadon,
    suZergLurkerEgg,
    suHeroRaszagal,
    suHeroSamirDuran,
    suHeroAlexeiStukov,
    suSpecialMapRevealer,
    suHeroGerardDuGalle,
    suZergLurker,
    suHeroInfestedDuran,
    suSpellDisruptionWeb,
    suTerranCommandCenter,
    suTerranComsatStation,
    suTerranNuclearSilo,
    suTerranSupplyDepot,
    suTerranRefinery,
    suTerranBarracks,
    suTerranAcademy,
    suTerranFactory,
    suTerranStarport,
    suTerranControlTower,
    suTerranScienceFacility,
    suTerranCovertOps,
    suTerranPhysicsLab,
    suUnusedTerran1,
    suTerranMachineShop,
    suUnusedTerran2,
    suTerranEngineeringBay,
    suTerranArmory,
    suTerranMissileTurret,
    suTerranBunker,
    suSpecialCrashedNoradII,
    suSpecialIonCannon,
    suPowerupUrajCrystal,
    suPowerupKhalisCrystal,
    suZergInfestedCommandCenter,
    suZergHatchery,
    suZergLair,
    suZergHive,
    suZergNydusCanal,
    suZergHydraliskDen,
    suZergDefilerMound,
    suZergGreaterSpire,
    suZergQueensNest,
    suZergEvolutionChamber,
    suZergUltraliskCavern,
    suZergSpire,
    suZergSpawningPool,
    suZergCreepColony,
    suZergSporeColony,
    suUnusedZerg1,
    suZergSunkenColony,
    suSpecialOvermindWithShell,
    suSpecialOvermind,
    suZergExtractor,
    suSpecialMatureChrysalis,
    suSpecialCerebrate,
    suSpecialCerebrateDaggoth,
    suUnusedZerg2,
    suProtossNexus,
    suProtossRoboticsFacility,
    suProtossPylon,
    suProtossAssimilator,
    suUnusedProtoss1,
    suProtossObservatory,
    suProtossGateway,
    suUnusedProtoss2,
    suProtossPhotonCannon,
    suProtossCitadelofAdun,
    suProtossCyberneticsCore,
    suProtossTemplarArchives,
    suProtossForge,
    suProtossStargate,
    suSpecialStasisCellPrison,
    suProtossFleetBeacon,
    suProtossArbiterTribunal,
    suProtossRoboticsSupportBay,
    suProtossShieldBattery,
    suSpecialKhaydarinCrystalForm,
    suSpecialProtossTemple,
    suSpecialXelNagaTemple,
    suResourceMineralField1,
    suResourceMineralField2,
    suResourceMineralField3,
    suUnusedCave,
    suUnusedCaveIn,
    suUnusedCantina,
    suUnusedMiningPlatform,
    suUnusedIndependantCommandCenter,
    suSpecialIndependantStarport,
    suUnusedIndependantJumpGate,
    suUnusedRuins,
    suUnusedKhaydarinCrystalFormation,
    suResourceVespeneGeyser,
    suSpecialWarpGate,
    suSpecialPsiDisrupter,
    suUnusedZergMarker,
    suUnusedTerranMarker,
    suUnusedProtossMarker,
    suSpecialZergBeacon,
    suSpecialTerranBeacon,
    suSpecialProtossBeacon,
    suSpecialZergFlagBeacon,
    suSpecialTerranFlagBeacon,
    suSpecialProtossFlagBeacon,
    suSpecialPowerGenerator,
    suSpecialOvermindCocoon,
    suSpellDarkSwarm,
    suSpecialFloorMissileTrap,
    suSpecialFloorHatch,
    suSpecialLeftUpperLevelDoor,
    suSpecialRightUpperLevelDoor,
    suSpecialLeftPitDoor,
    suSpecialRightPitDoor,
    suSpecialFloorGunTrap,
    suSpecialWallMissileTrap,
    suSpecialWallFlameTrap,
    suSpecialRightWallMissileTrap,
    suSpecialRightWallFlameTrap,
    suSpecialStartLocation,
    suPowerupFlag,
    suPowerupYoungChrysalis,
    suPowerupPsiEmitter,
    suPowerupDataDisk,
    suPowerupKhaydarinCrystal,
    suPowerupMineralClusterType1,
    suPowerupMineralClusterType2,
    suPowerupProtossGasOrbType1,
    suPowerupProtossGasOrbType2,
    suPowerupZergGasSacType1,
    suPowerupZergGasSacType2,
    suPowerupTerranGasTankType1,
    suPowerupTerranGasTankType2,
    suNone,
    suAnyUnit,
    suMen,
    suBuildings,
    suFactories,
    suResourceOre,
    suResourceGas,
    suResourceOreAndGas,
    suScoreUnits,
    suScoreBuildings,
    suScoreUnitsAndBuildings,
    suScoreKills,
    suScoreRazings,
    suScoreKillsAndRazings,
    suScoreTotal,
    suScoreCustom,
    suCountdown,
    suConst,
    suSwitch);

const
  StarcraftUnitIdentifier: array[low(TStarcraftUnit)..high(TStarcraftUnit)] of string =
   ('Terran.Marine',
    'Terran.Ghost',
    'Terran.Vulture',
    'Terran.Goliath',
    'Terran.GoliathTurret',
    'Terran.SiegeTankTankMode',
    'Terran.SiegeTankTankModeTurret',
    'Terran.SCV',
    'Terran.Wraith',
    'Terran.ScienceVessel',
    'Hero.GuiMontag',
    'Terran.Dropship',
    'Terran.Battlecruiser',
    'Terran.VultureSpiderMine',
    'Terran.NuclearMissile',
    'Terran.Civilian',
    'Hero.SarahKerrigan',
    'Hero.AlanSchezar',
    'Hero.AlanSchezarTurret',
    'Hero.JimRaynorVulture',
    'Hero.JimRaynorMarine',
    'Hero.TomKazansky',
    'Hero.Magellan',
    'Hero.EdmundDukeTankMode',
    'Hero.EdmundDukeTankModeTurret',
    'Hero.EdmundDukeSiegeMode',
    'Hero.EdmundDukeSiegeModeTurret',
    'Hero.ArcturusMengsk',
    'Hero.Hyperion',
    'Hero.NoradII',
    'Terran.SiegeTankSiegeMode',
    'Terran.SiegeTankSiegeModeTurret',
    'Terran.Firebat',
    'Spell.ScannerSweep',
    'Terran.Medic',
    'Zerg.Larva',
    'Zerg.Egg',
    'Zerg.Zergling',
    'Zerg.Hydralisk',
    'Zerg.Ultralisk',
    'Zerg.Broodling',
    'Zerg.Drone',
    'Zerg.Overlord',
    'Zerg.Mutalisk',
    'Zerg.Guardian',
    'Zerg.Queen',
    'Zerg.Defiler',
    'Zerg.Scourge',
    'Hero.Torrasque',
    'Hero.Matriarch',
    'Zerg.InfestedTerran',
    'Hero.InfestedKerrigan',
    'Hero.UncleanOne',
    'Hero.HunterKiller',
    'Hero.DevouringOne',
    'Hero.KukulzaMutalisk',
    'Hero.KukulzaGuardian',
    'Hero.Yggdrasill',
    'Terran.Valkyrie',
    'Zerg.Cocoon',
    'Protoss.Corsair',
    'Protoss.DarkTemplar',
    'Zerg.Devourer',
    'Protoss.DarkArchon',
    'Protoss.Probe',
    'Protoss.Zealot',
    'Protoss.Dragoon',
    'Protoss.HighTemplar',
    'Protoss.Archon',
    'Protoss.Shuttle',
    'Protoss.Scout',
    'Protoss.Arbiter',
    'Protoss.Carrier',
    'Protoss.Interceptor',
    'Hero.DarkTemplar',
    'Hero.Zeratul',
    'Hero.TassadarZeratulArchon',
    'Hero.FenixZealot',
    'Hero.FenixDragoon',
    'Hero.Tassadar',
    'Hero.Mojo',
    'Hero.Warbringer',
    'Hero.Gantrithor',
    'Protoss.Reaver',
    'Protoss.Observer',
    'Protoss.Scarab',
    'Hero.Danimoth',
    'Hero.Aldaris',
    'Hero.Artanis',
    'Critter.Rhynadon',
    'Critter.Bengalaas',
    'Special.CargoShip',
    'Special.MercenaryGunship',
    'Critter.Scantid',
    'Critter.Kakaru',
    'Critter.Ragnasaur',
    'Critter.Ursadon',
    'Zerg.LurkerEgg',
    'Hero.Raszagal',
    'Hero.SamirDuran',
    'Hero.AlexeiStukov',
    'Special.MapRevealer',
    'Hero.GerardDuGalle',
    'Zerg.Lurker',
    'Hero.InfestedDuran',
    'Spell.DisruptionWeb',
    'Terran.CommandCenter',
    'Terran.ComsatStation',
    'Terran.NuclearSilo',
    'Terran.SupplyDepot',
    'Terran.Refinery',
    'Terran.Barracks',
    'Terran.Academy',
    'Terran.Factory',
    'Terran.Starport',
    'Terran.ControlTower',
    'Terran.ScienceFacility',
    'Terran.CovertOps',
    'Terran.PhysicsLab',
    'Unused.Terran1',
    'Terran.MachineShop',
    'Unused.Terran2',
    'Terran.EngineeringBay',
    'Terran.Armory',
    'Terran.MissileTurret',
    'Terran.Bunker',
    'Special.CrashedNoradII',
    'Special.IonCannon',
    'Powerup.UrajCrystal',
    'Powerup.KhalisCrystal',
    'Zerg.InfestedCommandCenter',
    'Zerg.Hatchery',
    'Zerg.Lair',
    'Zerg.Hive',
    'Zerg.NydusCanal',
    'Zerg.HydraliskDen',
    'Zerg.DefilerMound',
    'Zerg.GreaterSpire',
    'Zerg.QueensNest',
    'Zerg.EvolutionChamber',
    'Zerg.UltraliskCavern',
    'Zerg.Spire',
    'Zerg.SpawningPool',
    'Zerg.CreepColony',
    'Zerg.SporeColony',
    'Unused.Zerg1',
    'Zerg.SunkenColony',
    'Special.OvermindWithShell',
    'Special.Overmind',
    'Zerg.Extractor',
    'Special.MatureChrysalis',
    'Special.Cerebrate',
    'Special.CerebrateDaggoth',
    'Unused.Zerg2',
    'Protoss.Nexus',
    'Protoss.RoboticsFacility',
    'Protoss.Pylon',
    'Protoss.Assimilator',
    'Unused.Protoss1',
    'Protoss.Observatory',
    'Protoss.Gateway',
    'Unused.Protoss2',
    'Protoss.PhotonCannon',
    'Protoss.CitadelofAdun',
    'Protoss.CyberneticsCore',
    'Protoss.TemplarArchives',
    'Protoss.Forge',
    'Protoss.Stargate',
    'Special.StasisCellPrison',
    'Protoss.FleetBeacon',
    'Protoss.ArbiterTribunal',
    'Protoss.RoboticsSupportBay',
    'Protoss.ShieldBattery',
    'Special.KhaydarinCrystalForm',
    'Special.ProtossTemple',
    'Special.XelNagaTemple',
    'Resource.MineralField1',
    'Resource.MineralField2',
    'Resource.MineralField3',
    'Unused.Cave',
    'Unused.CaveIn',
    'Unused.Cantina',
    'Unused.MiningPlatform',
    'Unused.IndependantCommandCenter',
    'Special.IndependantStarport',
    'Unused.IndependantJumpGate',
    'Unused.Ruins',
    'Unused.KhaydarinCrystalFormation',
    'Resource.VespeneGeyser',
    'Special.WarpGate',
    'Special.PsiDisrupter',
    'Unused.ZergMarker',
    'Unused.TerranMarker',
    'Unused.ProtossMarker',
    'Special.ZergBeacon',
    'Special.TerranBeacon',
    'Special.ProtossBeacon',
    'Special.ZergFlagBeacon',
    'Special.TerranFlagBeacon',
    'Special.ProtossFlagBeacon',
    'Special.PowerGenerator',
    'Special.OvermindCocoon',
    'Spell.DarkSwarm',
    'Special.FloorMissileTrap',
    'Special.FloorHatch',
    'Special.LeftUpperLevelDoor',
    'Special.RightUpperLevelDoor',
    'Special.LeftPitDoor',
    'Special.RightPitDoor',
    'Special.FloorGunTrap',
    'Special.WallMissileTrap',
    'Special.WallFlameTrap',
    'Special.RightWallMissileTrap',
    'Special.RightWallFlameTrap',
    'Special.StartLocation',
    'Powerup.Flag',
    'Powerup.YoungChrysalis',
    'Powerup.PsiEmitter',
    'Powerup.DataDisk',
    'Powerup.KhaydarinCrystal',
    'Powerup.MineralClusterType1',
    'Powerup.MineralClusterType2',
    'Powerup.ProtossGasOrbType1',
    'Powerup.ProtossGasOrbType2',
    'Powerup.ZergGasSacType1',
    'Powerup.ZergGasSacType2',
    'Powerup.TerranGasTankType1',
    'Powerup.TerranGasTankType2',
    'None',
    'AnyUnit',
    'Men',
    'Buildings',
    'Factories',
    'ResourceOre',
    'ResourceGas',
    'ResourceOreAndGas',
    'ScoreUnits',
    'ScoreBuildings',
    'ScoreUnitsAndBuildings',
    'ScoreKills',
    'ScoreRazings',
    'ScoreKillsAndRazings',
    'ScoreTotal',
    'ScoreCustom',
    'Countdown',
    'Const',
    'Switch');

var
  StarcraftUnitPrefixes: TStringList;
  StarcraftUnitSplitIdentifier: array[TStarcraftUnit] of record
    Prefix: string;
    PartialName: string;
  end;

const
  NonKillableUnits: array[1..52] of TStarcraftUnit =
   (suPowerupDataDisk,
    suPowerupFlag,
    suPowerupUrajCrystal,
    suPowerupKhalisCrystal,
    suPowerupKhaydarinCrystal,
    suPowerupPsiEmitter,
    suResourceMineralField1,
    suResourceMineralField2,
    suResourceMineralField3,
    suResourceVespeneGeyser,
    suSpecialZergBeacon,
    suSpecialTerranBeacon,
    suSpecialProtossBeacon,
    suSpecialZergFlagBeacon,
    suSpecialTerranFlagBeacon,
    suSpecialProtossFlagBeacon,
    suTerranGoliathTurret,
    suTerranSiegeTankTankModeTurret,
    suTerranSiegeTankSiegeModeTurret,
    suTerranNuclearMissile,
    suHeroAlanSchezarTurret,
    suHeroEdmundDukeSiegeModeTurret,
    suHeroEdmundDukeTankModeTurret,
    suSpecialCargoShip,
    suSpecialMercenaryGunship,
    suSpecialMapRevealer,
    suUnusedZerg1,
    suUnusedZerg2,
    suUnusedProtoss1,
    suUnusedProtoss2,
    suSpecialKhaydarinCrystalForm,
    suUnusedCantina,
    suUnusedMiningPlatform,
    suUnusedIndependantCommandCenter,
    suUnusedIndependantJumpGate,
    suSpecialIndependantStarport,
    suUnusedRuins,
    suUnusedKhaydarinCrystalFormation,
    suUnusedZergMarker,
    suUnusedTerranMarker,
    suUnusedProtossMarker,
    suSpecialFloorHatch,
    suSpecialLeftUpperLevelDoor,
    suSpecialRightUpperLevelDoor,
    suSpecialLeftPitDoor,
    suSpecialRightPitDoor,
    suSpecialStartLocation,
    suUnusedCaveIn,
    suUnusedCave,
    suSpellScannerSweep,
    suSpellDisruptionWeb,
    suSpellDarkSwarm);

implementation

function IntToPlayer(APlayer: integer): TPlayer;
begin
  result := TPlayer(ord(plPlayer1)+APlayer-1);
end;

function IsUniquePlayer(APlayers: TPlayers): boolean;
var count: integer;
  pl: TPlayer;
begin
  if APlayers = [plCurrentPlayer] then exit(true);
  count := 0;
  for pl := succ(plNone) to high(TPlayer) do
  begin
    if pl in APlayers then
    begin
      if pl > plPlayer12 then exit(false);
      inc(count);
    end;
  end;
  exit(count=1);
end;

procedure InitStarcraftUnitPrefixes;
var
  posDot, idx: integer;
  prefix: String;
  u: TStarcraftUnit;
begin
  StarcraftUnitPrefixes := TStringList.Create;
  for u := low(StarcraftUnitIdentifier) to high(StarcraftUnitIdentifier) do
  begin
    posDot := pos('.', StarcraftUnitIdentifier[u]);
    if posDot > 0 then
    begin
      prefix := copy(StarcraftUnitIdentifier[u], 1, posDot-1);
      if StarcraftUnitPrefixes.IndexOf(prefix) = -1 then
        idx := StarcraftUnitPrefixes.Add(prefix)
      else
        idx := StarcraftUnitPrefixes.IndexOf(prefix);
      StarcraftUnitSplitIdentifier[u].Prefix:= StarcraftUnitPrefixes[idx];
      StarcraftUnitSplitIdentifier[u].PartialName := StarcraftUnitIdentifier[u].Substring(posDot);
    end else
    begin
      StarcraftUnitSplitIdentifier[u].Prefix:= '';
      StarcraftUnitSplitIdentifier[u].PartialName := StarcraftUnitIdentifier[u];
    end;

  end;
end;

initialization

  InitStarcraftUnitPrefixes;

finalization

  StarcraftUnitPrefixes.Free;

end.

